// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/other/Footer";
import { Aside } from "@/components/other/Aside";
import { ClerkProvider } from "@clerk/nextjs";
import { auth } from "@clerk/nextjs/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
   const {userId} =  await auth();
  const hasSidebar = !!userId; // logged-in → show aside → shift layout

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <div className="flex min-h-screen">
            {hasSidebar && <Aside />}
            <main className={
              hasSidebar
                ? "flex-1 lg:ml-64"      // shift right for sidebar
                : "flex-1 pt-16"         // top padding for public header
            }>
              <div>{children}
              <Footer /></div>
            </main>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
